Repository reactplay/react-play, pull requests merged in 2022-05, with the labels that each got.

#119 a beautiful wall clock
  src/meta/play-meta.js
  src/plays/analog-clock/AnalogClock.css
  src/plays/analog-clock/AnalogClock.jsx
  src/plays/analog-clock/Readme.md
  src/plays/analog-clock/cover.png
  src/plays/index.js
Labels: review ready

#125 fix content overflow of tag list
  src/common/playlists/playlist.css
Labels: review ready

#74 New play - Keeper App
  package.json
  src/common/home/Home.jsx
  src/index.js
  src/meta/play-meta.js
  src/plays/index.js
  src/plays/keeper/CreateArea.jsx
  src/plays/keeper/Header.jsx
  src/plays/keeper/Hooks/useLocalStorage.js
  src/plays/keeper/Keeper.css
  src/plays/keeper/Keeper.jsx
  src/plays/keeper/Notes.jsx
  src/plays/keeper/README.md
Labels: work-in-progress

#85 Enabling Comments and Reactions for the Plays
  .gitignore
  package.json
  src/App.css
  src/common/components/Comment.jsx
  src/common/components/LevelBadge.jsx
  src/common/header/Header.jsx
  src/common/header/HeaderNav.jsx
  src/common/home/Home.jsx
  src/common/home/home.css
  src/common/index.js
  src/common/playideas/PlayIdeas.jsx
  src/common/playideas/ideas.json
  src/common/playideas/playIdeas.css
  src/common/playlists/PlayHeader.jsx
  src/common/playlists/PlayHeaderActions.jsx
  src/common/playlists/PlayHeaderInfo.jsx
  src/common/playlists/playlist.css
  src/common/routing/RouteDefs.jsx
Labels: work-in-progress

#209 [Feature] Added feature to allow users to select preferred styling lang
  CREATE-PLAY.md
  plop-templates/component_js.hbs
  plop-templates/component_ts.hbs
  plop-templates/style_css.hbs
  plop-templates/style_scss.hbs
  plopfile.js
  screens/plop-create.png
Labels: review ready

#170 a Simple and Fun Quiz App
  src/meta/play-meta.js
  src/plays/fun-quiz/EndScreen.jsx
  src/plays/fun-quiz/FrontScreen.jsx
  src/plays/fun-quiz/FrontScreen.scss
  src/plays/fun-quiz/FunQuiz.jsx
  src/plays/fun-quiz/FunQuiz.scss
  src/plays/fun-quiz/QuizScreen.jsx
  src/plays/fun-quiz/QuizScreen.scss
  src/plays/fun-quiz/Readme.md
  src/plays/fun-quiz/_variables.scss
  src/plays/fun-quiz/confuse.gif
  src/plays/fun-quiz/options.json
  src/plays/index.js
Labels: review ready

#198 Create calendar react-play
  package.json
  src/meta/play-meta.js
  src/plays/calendar/Calendar.scss
  src/plays/calendar/Calendar.tsx
  src/plays/calendar/CalendarDayTile.tsx
  src/plays/calendar/CalendarEvent.tsx
  src/plays/calendar/CalendarEventForm.tsx
  src/plays/calendar/CalendarEventInfo.tsx
  src/plays/calendar/CalendarEvents.tsx
  src/plays/calendar/CalendarEventsMore.tsx
  src/plays/calendar/CalendarGrid.tsx
  src/plays/calendar/CalendarNavigation.tsx
  src/plays/calendar/Context.tsx
  src/plays/calendar/EventType.ts
  src/plays/calendar/ModalContainer.tsx
  src/plays/calendar/Readme.md
  src/plays/calendar/cover.png
  src/plays/calendar/utils.tsx
  src/plays/index.js
Labels: Review-InProgress

#224 Fix #212 🐛 [Bug report]: XML Sitemap is not linked in robots.txt file and other SEO issues
  public/index.html
  public/robots.txt
  public/sitemap.xml
  src/meta/DefMeta.jsx
Labels: Review-InProgress

#208 Tic Tac Toe Game
  src/meta/play-meta.js
  src/plays/index.js
  src/plays/tic-tac-toe-game/Readme.md
  src/plays/tic-tac-toe-game/TicTacToeGame.jsx
  src/plays/tic-tac-toe-game/components/Game.jsx
  src/plays/tic-tac-toe-game/cover.png
  src/plays/tic-tac-toe-game/styles/tic-tac-toe-tj.css
Labels: Review-InProgress

#204 Registration form validation without any library
  src/meta/play-meta.js
  src/plays/index.js
  src/plays/registration-form/Readme.md
  src/plays/registration-form/Registration-form.css
  src/plays/registration-form/RegistrationForm.jsx
  src/plays/registration-form/cover.png
Labels: Review-InProgress

#222 styling play not found
  src/common/playlists/PlayList.jsx
  src/common/playlists/playlist.css
  src/images/img-oops.svg
Labels: Review-InProgress

#162 added quizeo play
  package.json
  src/common/routing/RouteDefs.jsx
  src/meta/play-meta.js
  src/plays/index.js
  src/plays/quizeo/Readme.md
  src/plays/quizeo/cover.png
  src/plays/quizeo/src/Quizeo.jsx
  src/plays/quizeo/src/components/directory/directory.component.jsx
  src/plays/quizeo/src/components/directory/directory.styles.css
  src/plays/quizeo/src/components/header/header.component.js
  src/plays/quizeo/src/components/header/header.styles.css
  src/plays/quizeo/src/components/menu-item/menu-item.styles.css
  src/plays/quizeo/src/components/menu-item/menuItem.component.js
  src/plays/quizeo/src/components/questions/questions.component.js
  src/plays/quizeo/src/components/questions/questions.styles.css
  src/plays/quizeo/src/data/movie.data.jsx
  src/plays/quizeo/src/pages/moviePage/moviePage.component.js
  src/plays/quizeo/src/pages/score-page/score.component.js
  src/plays/quizeo/src/pages/score-page/score.styles.css
  src/plays/quizeo/src/quizeo.css
  src/plays/quizeo/src/redux/directory/directory-reducer.js
  src/plays/quizeo/src/redux/directory/directory-selectors.js
  src/plays/quizeo/src/redux/movie/movie-reducer.js
  src/plays/quizeo/src/redux/movie/movieSelector.js
  src/plays/quizeo/src/redux/questions/question-types.js
  src/plays/quizeo/src/redux/questions/question.utils.js
  src/plays/quizeo/src/redux/questions/questions-action.js
  src/plays/quizeo/src/redux/root-reducer.js
  src/plays/quizeo/src/redux/store.js
Labels: Review-InProgress

#237 fixed typo "change"
  src/plays/dynamic-routes/DynamicRoutes.jsx
Labels: Review-InProgress
