Repository reactplay/react-play, pull requests merged in 2022-08, with the labels that each got.

#393 new play : countries-statics
  package.json
  src/meta/play-meta.js
  src/plays/countries-statics/CountriesStatics.jsx
  src/plays/countries-statics/Country.jsx
  src/plays/countries-statics/Map.jsx
  src/plays/countries-statics/Readme.md
  src/plays/countries-statics/cover.png
  src/plays/countries-statics/featues.json
Labels: Review-InProgress

#426 fix: Disable creating plays in Production
  src/common/createplay/CreatePlay.jsx
  src/common/routing/RouteDefs.jsx
  src/images/img-403.svg
Labels: Review-InProgress

#360 create react-play PWA
  package.json
  public/index.html
  public/logo.png
  public/logo152x152.png
  public/logo16x16.png
  public/logo192.png
  public/logo192x192.png
  public/logo24x24.png
  public/logo32x32.png
  public/logo48x48.png
  public/logo512.png
  public/manifest.json
  public/maskable_icon.png
  src/index.js
  src/registerServiceWorker.js
  src/service-worker.js
  tsconfig.json
Labels: Review-InProgress

#469 Fix #468 Plays page Is broken when we apply the filter
  src/common/services/request/query/fetch-plays-filter.js
Labels: review ready

#466 Added New Play - React Gradients
  package.json
  src/plays/react-gradients/GradientComponent.js
  src/plays/react-gradients/ReactGradients.js
  src/plays/react-gradients/Readme.md
  src/plays/react-gradients/cover.png
  src/plays/react-gradients/gradients.json
Labels: Review-InProgress

#478 Fix 🐛 Bug #443 : Play snap is broken: Cover image is not appearing
  src/common/playlists/PlayMeta.jsx
  src/common/services/string.js
  src/common/utils/playsUtil.js
Labels: review ready

#483 ✨ [Feature] #102: In filter modal creator dropdown should be a card list with image
  package.json
  src/common/search/FilterPlays.jsx
Labels: review ready, Review-InProgress

#481 Updated style for plays page for mobile
  src/App.css
  src/common/playlists/playlist.css
Labels: Review-InProgress

#433 Added Markdown Editor
  package.json
  src/plays/markdown-editor/Downloader.jsx
  src/plays/markdown-editor/MarkdownEditor.js
  src/plays/markdown-editor/Output.jsx
  src/plays/markdown-editor/Readme.md
  src/plays/markdown-editor/cover.png
  src/plays/markdown-editor/styles.css
Labels: Review-InProgress

#510 Adding netlify badge
  src/common/footer/ExtendedFooter.jsx
Labels: review ready

#509 ✨ [Feature #504]: Add umami in the tech stack page
  src/common/techstack/TechStackInfo.js
  src/images/umami.svg
Labels: review ready

#514 ✨ [Feature #498]: Add Error Boundaries
  package.json
  src/ErrorBoundary/ErrorBoundary.jsx
  src/ErrorBoundary/ErrorFallback.jsx
  src/common/playlists/playlist.css
  src/index.js
Labels: review ready
