Repository reactplay/react-play, pull requests merged in 2022-11, with the labels that each got.

#761 Image compressor play created (#721)
  package.json
  src/plays/image-compressor/ImageCompressor.js
  src/plays/image-compressor/Util.js
  src/plays/image-compressor/cover.png
  src/plays/image-compressor/readme.md
  src/plays/image-compressor/styles.css
Labels: Review-InProgress, hacktoberfest, Sachin-chaurasiya

#718 Quiz app
  src/plays/quiz-app/QuizApp.tsx
  src/plays/quiz-app/cover.png
  src/plays/quiz-app/types.ts
Labels: Angryman18

#732 Add Play : Play Fair Cipher
  src/plays/play-fair-cipher/PlayFairCipher.tsx
  src/plays/play-fair-cipher/cover.png
  src/plays/play-fair-cipher/readme.md
  src/plays/play-fair-cipher/styles.css
Labels: ammaaraslam, code-owners

#786 Added lib option to ts.config
  tsconfig.json
Labels: code-owners

#780 Infinite scrolling created
  src/plays/infinite-scrolling/InfiniteScrolling.js
  src/plays/infinite-scrolling/Posts.js
  src/plays/infinite-scrolling/cover.png
  src/plays/infinite-scrolling/readme.md
  src/plays/infinite-scrolling/styles.css
Labels: code-owners

#532 Issue-429-edit-play-flow
  src/common/404/PageNotFound.jsx
  src/common/components/Notification.jsx
  src/common/components/PlayForms.jsx
  src/common/createplay/CreatePlay.jsx
  src/common/createplay/utils.js
  src/common/playlists/PlayHeaderActions.jsx
  src/common/routing/RouteDefs.jsx
  src/common/services/plays.js
  src/common/services/request/query/edit-play.js
  src/common/services/request/query/tags.js
  src/index.js
Labels: enhancement, review ready

#809 edit play broken fix
  src/common/components/PlayForms.jsx
  src/common/createplay/utils.js
Labels: bug

#507 feature: configured ESLint/Prettier/Husky setup
  .eslintignore
  .eslintrc.json
  .prettierrc
  package.json
Labels: work-in-progress
