Repository reactplay/react-play, pull requests merged in 2022-06, with the labels that each got.

#270 added nhost support
  .gitignore
  nhost/config.yaml
  nhost/emails/en/email-confirm-change/body.html
  nhost/emails/en/email-confirm-change/subject.txt
  nhost/emails/en/email-verify/body.html
  nhost/emails/en/email-verify/subject.txt
  nhost/emails/en/password-reset/body.html
  nhost/emails/en/password-reset/subject.txt
  nhost/emails/en/signin-passwordless/body.html
  nhost/emails/en/signin-passwordless/subject.txt
  nhost/emails/fr/email-confirm-change/body.html
  nhost/emails/fr/email-confirm-change/subject.txt
  nhost/emails/fr/email-verify/body.html
  nhost/emails/fr/email-verify/subject.txt
  nhost/emails/fr/password-reset/body.html
  nhost/emails/fr/password-reset/subject.txt
  nhost/emails/fr/signin-passwordless/body.html
  nhost/emails/fr/signin-passwordless/subject.txt
  nhost/metadata/actions.graphql
  nhost/metadata/actions.yaml
  nhost/metadata/allow_list.yaml
  nhost/metadata/cron_triggers.yaml
  nhost/metadata/databases/databases.yaml
  nhost/metadata/databases/default/tables/auth_provider_requests.yaml
  nhost/metadata/databases/default/tables/auth_providers.yaml
  nhost/metadata/databases/default/tables/auth_refresh_tokens.yaml
  nhost/metadata/databases/default/tables/auth_roles.yaml
  nhost/metadata/databases/default/tables/auth_user_providers.yaml
  nhost/metadata/databases/default/tables/auth_user_roles.yaml
  nhost/metadata/databases/default/tables/auth_users.yaml
  nhost/metadata/databases/default/tables/public_levels.yaml
  nhost/metadata/databases/default/tables/public_play_tags.yaml
  nhost/metadata/databases/default/tables/public_plays.yaml
  nhost/metadata/databases/default/tables/public_tags.yaml
  nhost/metadata/databases/default/tables/storage_buckets.yaml
  nhost/metadata/databases/default/tables/storage_files.yaml
  nhost/metadata/databases/default/tables/tables.yaml
  nhost/metadata/query_collections.yaml
  nhost/metadata/remote_schemas.yaml
  nhost/metadata/rest_endpoints.yaml
  nhost/metadata/version.yaml
  nhost/migrations/default/1654239932355_init/up.sql
Labels: Review-InProgress

#243 Complete Password Generator UI
  src/plays/password-generator/PasswordGenerator.jsx
  src/plays/password-generator/password-generator-style.css
Labels: review ready

#287 Add Readme.md file for all the missing Plays!
  _config.yml
  plop-templates/play-readme.hbs
  src/plays/clock/Readme.md
  src/plays/counter/Readme.md
  src/plays/date-time-counter/Readme.md
  src/plays/movies/Readme.md
  src/plays/org-tree/Readme.md
  src/plays/why-react/Readme.md
Labels: review ready

#297 ✨ [Feature #296]: Add new idea - Image Gallery
  src/common/playideas/ideas.json
Labels: review ready

#292 Fix #291 🐛 [Bug report]: Fix grammatical error on README file
  README.md
Labels: documentation, enhancement

#258 simple live chat
  package.json
  src/meta/play-meta.js
  src/plays/index.js
  src/plays/simple-live-chat/Readme.md
  src/plays/simple-live-chat/SimpleLiveChat.jsx
  src/plays/simple-live-chat/_variables.scss
  src/plays/simple-live-chat/components/chat/chat-body.jsx
  src/plays/simple-live-chat/components/chat/chat-body.scss
  src/plays/simple-live-chat/components/chat/chat-footer.jsx
  src/plays/simple-live-chat/components/chat/chat-footer.scss
  src/plays/simple-live-chat/components/chat/chat-header.jsx
  src/plays/simple-live-chat/components/chat/chat-header.scss
  src/plays/simple-live-chat/components/chat/chat.jsx
  src/plays/simple-live-chat/components/chat/chat.scss
  src/plays/simple-live-chat/components/chat/components/User.jsx
  src/plays/simple-live-chat/components/chat/hooks/useDateFormat.js
  src/plays/simple-live-chat/components/signin-button.jsx
  src/plays/simple-live-chat/components/signin-button.scss
  src/plays/simple-live-chat/components/user/user.jsx
  src/plays/simple-live-chat/components/user/user.scss
  src/plays/simple-live-chat/firebase.js
  src/plays/simple-live-chat/images/github.png
  src/plays/simple-live-chat/images/icon.png
  src/plays/simple-live-chat/images/send.svg
  src/plays/simple-live-chat/images/twitter.png
  src/plays/simple-live-chat/images/user_icon.png
  src/plays/simple-live-chat/simpleLiveChat.scss
Labels: review ready

#350 🐛 Fixing the header style issue
  src/common/header/Header.jsx
Labels: review ready

#309 Feat new react-play: GitHub User Search
  package.json
  src/meta/play-meta.js
  src/plays/expanding-cards/ExpandingCards.jsx
  src/plays/github-user-search/GitHubUserCard.jsx
  src/plays/github-user-search/GitHubUserSearch.jsx
  src/plays/github-user-search/Readme.md
  src/plays/github-user-search/cover.png
  src/plays/index.js
  src/plays/simple-live-chat/firebase.js
  tailwind.config.js
Labels: Review-InProgress
