Repository reactplay/react-play, pull requests merged in 2022-10, with the labels that each got.

#569 update the z-index of .app-home-body-content class
  src/common/home/home.css
Labels: hacktoberfest, hacktoberfest-accepted

#565 Added Typing speed test play
  src/plays/typing-speed-test/TypingSpeedTest.js
  src/plays/typing-speed-test/components/ResultModal.js
  src/plays/typing-speed-test/components/Stats.js
  src/plays/typing-speed-test/components/Timer.js
  src/plays/typing-speed-test/components/TypingTest.js
  src/plays/typing-speed-test/components/Word.js
  src/plays/typing-speed-test/cover.png
  src/plays/typing-speed-test/readme.md
  src/plays/typing-speed-test/styles.css
  src/plays/typing-speed-test/utils/index.js
Labels: review ready, Review-InProgress, hacktoberfest, hacktoberfest-accepted

#581 Dev jokes js to ts
  src/plays/dev-jokes/DevJokes.tsx
  src/plays/dev-jokes/Readme.md
  src/plays/dev-jokes/Spinner.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#562 "Clear All" Button added to clear applied Filters
  src/common/modal/index.jsx
  src/common/search/FilterPlays.jsx
  src/common/search/search.css
Labels: hacktoberfest, hacktoberfest-accepted

#634 Update CREATE-PLAY docs
  CREATE-PLAY.md
Labels: hacktoberfest-accepted

#628 Fix footer nested link
  src/common/footer/Footer.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#638 Create Greeting.yml
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted

#606 Text Avatar Play
  src/plays/text-avatar/Readme.md
  src/plays/text-avatar/TextAvatar.tsx
  src/plays/text-avatar/components/Avatar/index.tsx
  src/plays/text-avatar/components/Avatar/style.scss
  src/plays/text-avatar/components/UserCard/index.tsx
  src/plays/text-avatar/components/UserCard/style.scss
  src/plays/text-avatar/constants.ts
  src/plays/text-avatar/cover.png
  src/plays/text-avatar/hooks/useFetchUser.ts
  src/plays/text-avatar/style.scss
  src/plays/text-avatar/types.ts
  src/plays/text-avatar/utils/index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#644 fix #643: div tag present as descendant of p tag
  src/common/footer/ExtendedFooter.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#640 lazy load contributor images
  src/common/home/Contributors.jsx
  src/common/playlists/PlayThumbnail.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#573 docs: grammatical errors fixed
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#657 fix #655: key value for each play in featured plays
  src/common/playlists/FeaturedPlays.jsx
  src/common/playlists/PlayThumbnail.jsx
Labels: hacktoberfest-accepted

#621 new play-Download API response
  src/plays/download-fetch-response/CustomHooks/UseCustomFetchAPI.jsx
  src/plays/download-fetch-response/DownloadFetchResponse.jsx
  src/plays/download-fetch-response/Readme.md
  src/plays/download-fetch-response/cover.png
  src/plays/download-fetch-response/response.scss
Labels: hacktoberfest, hacktoberfest-accepted

#587 Fix Edit event modal pop-up on save click
  src/plays/calendar/CalendarEventForm.tsx
Labels: hacktoberfest

#674 Issue 673- Made description as single line field
  src/common/createplay/create-play-form-template.js
Labels: hacktoberfest, hacktoberfest-accepted

#678 Update hackrplay logo with new date
  src/common/activities/hackathon/Logo.png
Labels: hacktoberfest-accepted

#681 fix #680: umami and nhost svg colour change
  src/App.css
  src/common/techstack/TechStacks.jsx
  src/images/nhost.svg
  src/images/umami.svg
Labels: hacktoberfest-accepted

#676 Fixed #600: Empty Note error
  src/plays/keeper/CreateArea.jsx
  src/plays/keeper/Keeper.css
Labels: review ready, hacktoberfest-accepted

#662 Update Create Issue template format
  .github/ISSUE_TEMPLATE/----bug-report---.md
  .github/ISSUE_TEMPLATE/---feature-request---.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/new-play.md
  .github/ISSUE_TEMPLATE/new-play.yml
Labels: hacktoberfest, hacktoberfest-accepted

#661 Fixed: #590 add emojipedia play
  src/plays/emojipedia/Emojipedia.js
  src/plays/emojipedia/components/EmojiCard.js
  src/plays/emojipedia/components/SkeletonCard.js
  src/plays/emojipedia/config.js
  src/plays/emojipedia/cover.png
  src/plays/emojipedia/readme.md
Labels: hacktoberfest

#616 Pokemon stats from js to ts
  src/plays/pokemon-stats/PokemonStats.tsx
  src/plays/pokemon-stats/Readme.md
  src/plays/pokemon-stats/components/Pokemoncard.tsx
  src/plays/pokemon-stats/components/Search.tsx
  src/plays/pokemon-stats/types.d.ts
Labels: hacktoberfest-accepted

#651 Personal profile card
  src/globals.d.ts
  src/plays/personal-profile-card/PersonalProfileCard.tsx
  src/plays/personal-profile-card/Readme.md
  src/plays/personal-profile-card/components/profile-card.tsx
  src/plays/personal-profile-card/components/profile-form.tsx
  src/plays/personal-profile-card/cover.png
  src/plays/personal-profile-card/images/edit.svg
  src/plays/personal-profile-card/images/placeholder_cover.jpg
  src/plays/personal-profile-card/images/placeholder_profile.png
  src/plays/personal-profile-card/index.css
  src/plays/personal-profile-card/types/index.ts
  tsconfig.json
Labels: review ready, hacktoberfest

#704 🐛 Issue 698: Search Bug in the Emojipedia Play
  src/plays/emojipedia/Emojipedia.js
Labels: hacktoberfest-accepted

#647 Fix: heading level hierarchy
  src/common/createplay/CreatePlay.jsx
  src/common/defaultBanner/DefaultBanner.jsx
  src/common/home/Contributors.jsx
  src/common/home/Home.jsx
  src/common/playideas/PlayIdeas.jsx
  src/common/playlists/FeaturedPlays.jsx
  src/common/techstack/TechStacks.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#659 Added Contributor Adding Workflow
  .github/workflows/contributions.yml
Labels: hacktoberfest, hacktoberfest-accepted

#736 Fix #735: Remove unused imports and states
  src/common/activities/hackathon/HackathonBanner.jsx
  src/common/home/Home.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#734 Fix #733: Add missing alt property for images
  src/common/activities/hackathon/HackathonBanner.jsx
  src/plays/code-editor/Modal.jsx
  src/plays/personal-profile-card/components/profile-form.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#726 [Fix] Issue-711 image loosing its aspect ratio
  src/plays/social-card/social-card.css
Labels: hacktoberfest, hacktoberfest-accepted

#596 Added Weather play
  src/plays/weather/Weather.js
  src/plays/weather/components/CityInput.js
  src/plays/weather/components/ForecastData.js
  src/plays/weather/components/ForecastItem.js
  src/plays/weather/components/WeatherDetail.js
  src/plays/weather/components/WeatherOutput.js
  src/plays/weather/readme.md
  src/plays/weather/styles.scss
  src/plays/weather/utils/index.js
Labels: hacktoberfest

#679 [Play] - News Feed Application
  src/plays/news-feed-application/NewsFeedApplication.jsx
  src/plays/news-feed-application/component/CustomToggleButtonGroup.jsx
  src/plays/news-feed-application/component/NewsCard.jsx
  src/plays/news-feed-application/countriesAndCategories.js
  src/plays/news-feed-application/cover.png
  src/plays/news-feed-application/readme.md
  src/plays/news-feed-application/styles.css
Labels: review ready, hacktoberfest-accepted

#731 Added error message
  src/plays/emojipedia/Emojipedia.js
Labels: hacktoberfest, hacktoberfest-accepted

#723 Responsive side menu fix
  src/common/header/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#715 [Play] Multi-Select Component
  src/plays/multiselect-component/MultiselectComponent.tsx
  src/plays/multiselect-component/Readme.md
  src/plays/multiselect-component/components/CloseOptionsIcon.tsx
  src/plays/multiselect-component/components/MultiSelect.tsx
  src/plays/multiselect-component/components/OpenOptionsIcon.tsx
  src/plays/multiselect-component/cover.png
  src/plays/multiselect-component/styles.scss
Labels: hacktoberfest, hacktoberfest-accepted

#756 675 feature request adding env file for dev mode during create react play process
  .env.development
  README.md
Labels: review ready, hacktoberfest-accepted

#752 Fix #751 : Add .vscode to the .gitignore file
  .gitignore
Labels: hacktoberfest-accepted

#744 Text underline moved to the back
  src/common/playcreated/play-created.scss
Labels: hacktoberfest-accepted

#764 763 feature request configure repository with gitpod
  .gitpod.yml
  README.md
Labels: hacktoberfest-accepted

#745 Get motivated play
  src/plays/motivate-me/MotivateMe.js
  src/plays/motivate-me/README.md
  src/plays/motivate-me/assets/background1.jpg
  src/plays/motivate-me/components/cards/index.css
  src/plays/motivate-me/components/cards/index.js
  src/plays/motivate-me/components/header/index.css
  src/plays/motivate-me/components/header/index.js
  src/plays/motivate-me/components/search-bar/index.css
  src/plays/motivate-me/components/search-bar/index.js
  src/plays/motivate-me/container/index.js
  src/plays/motivate-me/container/motivational_quote_card_container_main.css
  src/plays/motivate-me/cover.png
  src/plays/motivate-me/data.js
  src/plays/motivate-me/motivate_me_style.css
Labels: hacktoberfest-accepted

#646 Added Back Button in Pokemon-Stats
  src/plays/pokemon-stats/PokemonStats.tsx
  src/plays/pokemon-stats/components/Pokemoncard.tsx
  src/plays/pokemon-stats/components/pokecard.css
  src/plays/pokemon-stats/types.d.ts
Labels: hacktoberfest-accepted

#755 Svg color change
  src/common/playlists/playlist.css
Labels: hacktoberfest-accepted

#739 P5js Sierpinski Triangle
  package.json
  src/plays/sierpinski-triangle/README.md
  src/plays/sierpinski-triangle/SierpinskiTriangle.tsx
  src/plays/sierpinski-triangle/Triangle.ts
  src/plays/sierpinski-triangle/constants.ts
  src/plays/sierpinski-triangle/utils/index.ts
Labels: hacktoberfest, hacktoberfest-accepted, atapas

#614 Update Pull Request template
  .github/pull_request_template.md
Labels: hacktoberfest, hacktoberfest-accepted, atapas

#772 Plays responsiveness
  package.json
  src/plays/download-fetch-response/DownloadFetchResponse.jsx
  src/plays/download-fetch-response/response.scss
  src/plays/multiselect-component/styles.scss
Labels: hacktoberfest, hacktoberfest-accepted, atapas

#748 [Play]: Savings Calculator
  package.json
  src/plays/savings-calculator/SavingsCalculator.jsx
  src/plays/savings-calculator/components/SavingOptions/index.jsx
  src/plays/savings-calculator/components/SavingOptions/savingOptions.scss
  src/plays/savings-calculator/components/SavingOptions/tests/SavingOptionsTest.test.jsx
  src/plays/savings-calculator/components/Total/index.jsx
  src/plays/savings-calculator/components/Total/tests/TotalTest.test.jsx
  src/plays/savings-calculator/components/Total/total.scss
  src/plays/savings-calculator/cover.png
  src/plays/savings-calculator/images/arrow-down.png
  src/plays/savings-calculator/images/piggy-bank.png
  src/plays/savings-calculator/readme.md
  src/plays/savings-calculator/styles/_variables.scss
  src/plays/savings-calculator/styles/savingsCalculator.scss
  src/plays/savings-calculator/utils/getCalculatedSaving.js
  src/plays/savings-calculator/utils/getCurrencySymbol.js
Labels: hacktoberfest, hacktoberfest-accepted, Sachin-chaurasiya, code-owners

#759 Cleaning duplicate code in few .scss , .css files, imports
  src/App.css
  src/common/components/Like/Like.jsx
  src/common/components/Like/Like.scss
  src/common/createplay/CreatePlay.jsx
  src/common/header/Header.jsx
  src/common/header/HeaderNav.jsx
  src/common/home/home.css
  src/common/playcreated/play-created.scss
  src/common/services/plays.js
  src/plays/dynamic-routes/Navbar.jsx
  src/plays/fun-quiz/QuizScreen.scss
  src/plays/image-gallery/styles.css
  src/plays/quizeo/components/questions/questions.styles.css
  src/plays/simple-live-chat/components/chat/chat-body.scss
Labels: hacktoberfest, hacktoberfest-accepted, Sachin-chaurasiya, code-owners

#771 Fix #770 ✨ [Feature request]: Close Stale Issues and PRs workflow
  .github/workflows/greetings.yml
  .github/workflows/stale-issue-and-pr.yml
Labels: review ready, hacktoberfest-accepted

#762 Header icon color now changes on hover
  src/common/header/HeaderNav.jsx
  src/common/header/header.css
Labels: hacktoberfest-accepted, koustov

#767 Added Web3 Staking Dapp
  package.json
  src/plays/web3-staking-dapp/.gitignore
  src/plays/web3-staking-dapp/Readme.md
  src/plays/web3-staking-dapp/Web3StakingDapp.js
  src/plays/web3-staking-dapp/artifacts/build-info/5faf9c6c2f8753632f3c7c13937cd196.json
  src/plays/web3-staking-dapp/artifacts/contracts/Staking.sol/Staking.dbg.json
  src/plays/web3-staking-dapp/artifacts/contracts/Staking.sol/Staking.json
  src/plays/web3-staking-dapp/components/Navbar.js
  src/plays/web3-staking-dapp/constant.js
  src/plays/web3-staking-dapp/cover.png
  src/plays/web3-staking-dapp/images/polygon-matic-logo.svg
  src/plays/web3-staking-dapp/smart-contract/contracts/Staking.sol
  src/plays/web3-staking-dapp/smart-contract/hardhat.config.js
  src/plays/web3-staking-dapp/smart-contract/scripts/deploy.js
  src/plays/web3-staking-dapp/smart-contract/test/Staking.js
Labels: hacktoberfest-accepted, Sachin-chaurasiya

#750 Fix #749: Remove non-functioning imports and states
  src/plays/download-fetch-response/DownloadFetchResponse.jsx
  src/plays/image-gallery/Gallery.js
  src/plays/pokemon-stats/components/Search.tsx
  src/plays/typing-speed-test/components/ResultModal.js
Labels: hacktoberfest, hacktoberfest-accepted, koustov

#595 feat: support to select multiple filters
  package.json
  src/common/components/MultiSelect.jsx
  src/common/search/FilterPlays.jsx
  src/common/search/search-context.js
  src/common/services/request/query/fetch-plays-filter.js
Labels: hacktoberfest, koustov

#649 create ImageCollector play
  src/plays/image-collector/ImageCollector.js
  src/plays/image-collector/cover.png
  src/plays/image-collector/readme.md
  src/plays/image-collector/styles.css
Labels: hacktoberfest, koustov
