Repository reactplay/react-play, pull requests merged in 2023-03, with the labels that each got.

#1016 [#2PlaysAMonth] Digits Delight
  src/plays/digital-delight/DigitsDelight.js
  src/plays/digital-delight/Readme.md
  src/plays/digital-delight/components/CategoryFact.js
  src/plays/digital-delight/components/Categoryfact.css
  src/plays/digital-delight/components/DigitsDelightsConstant.js
  src/plays/digital-delight/components/Modal.css
  src/plays/digital-delight/components/Modal.js
  src/plays/digital-delight/components/Random.css
  src/plays/digital-delight/components/Random.js
  src/plays/digital-delight/components/TextFact.css
  src/plays/digital-delight/components/TextFact.js
  src/plays/digital-delight/components/Title.css
  src/plays/digital-delight/components/Title.js
  src/plays/digital-delight/components/images/date.png
  src/plays/digital-delight/components/images/math.png
  src/plays/digital-delight/components/images/year.png
  src/plays/digital-delight/cover.png
  src/plays/digital-delight/styles.css
Labels: #2PlaysAMonth

#1017 Play dictionary
  src/plays/play-dictionary/PlayDictionary.css
  src/plays/play-dictionary/PlayDictionary.js
  src/plays/play-dictionary/Readme.md
  src/plays/play-dictionary/ThemeConstant.js
  src/plays/play-dictionary/cover.png
Labels: Review-InProgress, #2PlaysAMonth

#1001 [#2PlaysAMonth] Pagination
  src/plays/pagination/Pagination.js
  src/plays/pagination/Readme.md
  src/plays/pagination/components/Card.jsx
  src/plays/pagination/components/Users.jsx
  src/plays/pagination/cover.png
  src/plays/pagination/hooks/useFetch.js
  src/plays/pagination/utils/paginate.js
Labels: #2PlaysAMonth

#1022 [#2PlaysAMonth]: Color Palettes Generator
  src/plays/color-palettes-generator/ColorPalettesGenerator.js
  src/plays/color-palettes-generator/Readme.md
  src/plays/color-palettes-generator/components/SingleColor.js
  src/plays/color-palettes-generator/components/utils.js
  src/plays/color-palettes-generator/cover.png
  src/plays/color-palettes-generator/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#1007 [#2PlaysAMonth]: Travel app
  package.json
  src/plays/travel-advisor/Readme.md
  src/plays/travel-advisor/TravelAdvisor.js
  src/plays/travel-advisor/api/travel_api.js
  src/plays/travel-advisor/components/DropDown.jsx
  src/plays/travel-advisor/components/Map.jsx
  src/plays/travel-advisor/components/Search.jsx
  src/plays/travel-advisor/cover.png
  src/plays/travel-advisor/styles.css
  src/plays/travel-advisor/styles/dropdown.css
  src/plays/travel-advisor/styles/search.css
Labels: Review-InProgress, #2PlaysAMonth

#1037 CodeNchill - [#2PlaysAMonth]
  package.json
  src/plays/codenchill/Codenchill.js
  src/plays/codenchill/Main.js
  src/plays/codenchill/Readme.md
  src/plays/codenchill/app/store.js
  src/plays/codenchill/assets/playing.gif
  src/plays/codenchill/data/track.js
  src/plays/codenchill/features/AudioPlayerTracks/AudioplayerContainer.js
  src/plays/codenchill/features/AudioPlayerTracks/TrackTile.js
  src/plays/codenchill/features/DisplayTrackControls/TrackControlSlice.js
  src/plays/codenchill/features/DisplayTrackControls/TrackControls.js
  src/plays/codenchill/features/Timer/GuideModal.js
  src/plays/codenchill/features/Timer/TimerContainer.js
  src/plays/codenchill/features/Timer/TimerControlSlice.js
  src/plays/codenchill/styles.css
  tailwind.config.js
Labels: #2PlaysAMonth

#974 [#2PlaysAMonth]: Image Gallery - Create a responsive image gallery by using the free Unsplash API
  package.json
  src/plays/image-gallery-using-unsplash-api/ImageGalleryUsingUnsplashApi.js
  src/plays/image-gallery-using-unsplash-api/Readme.md
  src/plays/image-gallery-using-unsplash-api/components/Photo.jsx
  src/plays/image-gallery-using-unsplash-api/components/searchBar.jsx
  src/plays/image-gallery-using-unsplash-api/cover.png
  src/plays/image-gallery-using-unsplash-api/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#1008 Emoji guess game
  src/plays/cricket-game/Readme.md
  src/plays/cricket-game/styles.css
  src/plays/emoji-game/App.css
  src/plays/emoji-game/EmojiGame.js
  src/plays/emoji-game/Readme.md
  src/plays/emoji-game/components/Instruction.js
  src/plays/emoji-game/components/buttn.css
  src/plays/emoji-game/components/buttn.js
  src/plays/emoji-game/components/emoji.js
  src/plays/emoji-game/components/list.css
  src/plays/emoji-game/components/list.js
  src/plays/emoji-game/components/welcome.css
  src/plays/emoji-game/components/welcome.js
  src/plays/emoji-game/cover.png
  src/plays/smart-converter/Readme.md
  src/plays/smart-converter/SmartConverter.js
  src/plays/smart-converter/styles.css
Labels: #2PlaysAMonth

#1038 [#2PlaysAMonth]: Wordle Game
  src/globals.d.ts
  src/plays/wordle/Readme.md
  src/plays/wordle/Wordle.tsx
  src/plays/wordle/assets/backspace.svg
  src/plays/wordle/components/EndScreen.tsx
  src/plays/wordle/components/KeyboardKey.tsx
  src/plays/wordle/components/WordleRow.tsx
  src/plays/wordle/components/WordleTile.tsx
  src/plays/wordle/data/words.ts
  src/plays/wordle/styles.css
  src/plays/wordle/types.ts
  src/plays/wordle/utils.ts
Labels: #2PlaysAMonth

#779 New Play: Checkout Page
  src/plays/shopping-cart/Readme.md
  src/plays/shopping-cart/ShoppingCart.tsx
  src/plays/shopping-cart/ShoppingCartTypes.interface.ts
  src/plays/shopping-cart/components/CartItem.tsx
  src/plays/shopping-cart/components/Container.tsx
  src/plays/shopping-cart/components/Navbar.tsx
  src/plays/shopping-cart/context.tsx
  src/plays/shopping-cart/cover.png
  src/plays/shopping-cart/data.ts
  src/plays/shopping-cart/reducer.ts
Labels: review ready, koustov

#1023 [#2PlaysAMonth]: Pixy - Pixel Art Creator
  package.json
  src/plays/pixy/Pixy.js
  src/plays/pixy/Readme.md
  src/plays/pixy/components/drawing-panel/DrawingPanel.css
  src/plays/pixy/components/drawing-panel/DrawingPanel.jsx
  src/plays/pixy/components/pixel/Pixel.css
  src/plays/pixy/components/pixel/Pixel.jsx
  src/plays/pixy/components/row/Row.css
  src/plays/pixy/components/row/Row.jsx
  src/plays/pixy/cover.png
  src/plays/pixy/styles.css
Labels: #2PlaysAMonth

#1069 ✨ [Feature request]: Update greeting workflow #1068
  .github/CODEOWNERS
  .github/workflows/greetings.yml
Labels: enhancement
