Repository reactplay/react-play, pull requests merged in 2023-10, with the labels that each got.

#1264 Changed Twitter icon to X
  src/common/components/SocialShare.jsx
  src/common/footer/ExtendedFooter.jsx
  src/common/header/HeaderNav.jsx
  src/common/header/header.css
  src/plays/social-card/CardDetails.jsx
Labels: review ready, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1279 ci: auto author assign for PRs #1252
  .github/workflows/auto-author-assign.yml
Labels: review ready, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1250 Clean up file path and import
  src/App.jsx
  src/common/home/Sponsors.jsx
  src/index.jsx
  src/plays/github-user-finder/components/ProfileCard.jsx
  src/plays/personal-profile-card/PersonalProfileCard.tsx
  src/plays/random-quote-card-generator/Components/CardContainer.jsx
  src/plays/react-transitions/PrioitySearch.jsx
  src/plays/react-transitions/ReactTransitions.jsx
  src/plays/react-transitions/TransitionSearch.jsx
  src/plays/video-preview/Card.tsx
Labels: review ready, waiting for merge

#1254 Bugs fix/cypress/1251
  cypress/e2e/homePage.cy.ts
  cypress/e2e/ideasPage.cy.ts
  cypress/e2e/leaderboardPage.cy.ts
  cypress/support/commands.ts
  cypress/support/constant.ts
Labels: review ready, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1296 chore: deleted unwanted files
  TestimonialModal.jsx
  Testtimonal.css
Labels: review ready, waiting for merge

#1308 Fix: Github Actions running on forked repos
  .github/workflows/auto-author-assign.yml
  .github/workflows/contributions.yml
  .github/workflows/cypress.yml
  .github/workflows/greetings.yml
  .github/workflows/stale-issue-and-pr.yml
Labels: review ready, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1316 chore: add labels to issue templates #1315
  .github/ISSUE_TEMPLATE/#2PlaysAMonth.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/new-play.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: waiting for merge, 💻 aspect: code

#1318 ci: add issue lock github action #1317
  .github/workflows/issue-lock.yml
Labels: workflow, waiting for merge, 💻 aspect: code

#1260 [Fix] Add React play api url in .env
  .env.development
  src/common/activities/ActivityBanner.jsx
  src/common/defaultBanner/DefaultBanner.jsx
  src/common/home/Home.jsx
  src/common/hooks/useContributors.js
Labels: review ready, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1294 [Feature] : custom scroll bar
  src/App.css
Labels: review ready, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1321 feat: updated GitHub star count number format
  .all-contributorsrc
  package.json
  src/common/activities/ActivityBanner.jsx
  src/common/defaultBanner/DefaultBanner.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#1313 Hangman Game is Developed and tested
  package.json
  src/plays/hangman-game/HangmanGame.tsx
  src/plays/hangman-game/Readme.md
  src/plays/hangman-game/components/Drawing.tsx
  src/plays/hangman-game/components/Keyboard.tsx
  src/plays/hangman-game/components/Main.tsx
  src/plays/hangman-game/components/Word.tsx
  src/plays/hangman-game/constants/constants.tsx
  src/plays/hangman-game/constants/wordList.json
  src/plays/hangman-game/cover.png
  src/plays/hangman-game/styled-components.tsx
  src/plays/hangman-game/styles.css
Labels: play request, waiting for reviewers, hacktoberfest, hacktoberfest-accepted

#1327 fix: overlapping icon over text
  src/common/home/home.css
Labels: hacktoberfest, hacktoberfest-accepted

#1339 remove umani script from index.html as it is not used since some month
  public/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#1337 Cleanup warnings on eslint. Formatted all and modified a typo for cre…
  package.json
  src/App.css
  src/common/home/home.css
  src/common/playlists/PlayThumbnail.jsx
  src/plays/codenchill/features/DisplayTrackControls/TrackControlSlice.js
  src/plays/cricket-game/components/EndGameScreen.jsx
  src/plays/cricket-game/components/Modal.jsx
  src/plays/cricket-game/components/TopBar.jsx
  src/plays/cricket-game/game/gameLogic.js
  src/plays/custommemesgenerator/Custommemesgenerator.jsx
  src/plays/digital-delight/components/CategoryFact.jsx
  src/plays/digital-delight/components/Modal.jsx
  src/plays/digital-delight/components/Title.jsx
  src/plays/hangman-game/Readme.md
  src/plays/hangman-game/components/Drawing.tsx
  src/plays/hangman-game/components/Keyboard.tsx
  src/plays/hangman-game/components/Word.tsx
  src/plays/hangman-game/constants/constants.tsx
  src/plays/hangman-game/styles.css
  src/plays/infinite-scroll-with-debouncing-concept/InfiniteScrollWithDebouncingConcept.jsx
  src/plays/multiplayer-tic-tac-toe/MultiplayerTicTacToe.tsx
  src/plays/multiselect-component/styles.scss
  src/plays/object-detector/ObjectDetector.jsx
  src/plays/random-quote-card-generator/Components/SideBarOperation.jsx
  src/plays/savings-calculator/components/SavingOptions/savingOptions.scss
  src/plays/savings-calculator/components/Total/total.scss
  src/plays/savings-calculator/styles/savingsCalculator.scss
  src/plays/self-clicking-button/SelfClickingButton.jsx
  src/plays/tube2tunes/Tube2tunes.jsx
Labels: waiting for reviewers, hacktoberfest, hacktoberfest-accepted

#1341 Fix/typo form
  src/common/components/PlayForms.jsx
Labels: waiting for reviewers, hacktoberfest, hacktoberfest-accepted

#1265 style: categorization on tech stack page
  src/App.css
  src/common/techstack/TechStackInfo.js
  src/common/techstack/TechStacks.css
  src/common/techstack/TechStacks.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#1336 fix: Update and rename auto-author-assign.yml to author-assign.yml
  .github/workflows/author-assign.yml
Labels: waiting for merge

#1333 Update packages version and ready for pnpm
  .eslintrc.js
  .gitignore
  package.json
  pnpm-lock.yaml
  src/plays/2048/Game2048Styles/game.css
  src/plays/analog-clock/AnalogClock.css
  src/plays/basic-calculator/styles.css
  src/plays/context-with-real-usecases/contextWithRealUsecases.css
  src/plays/cricket-game/styles.css
  src/plays/custommemesgenerator/Custommemesgenerator.css
  src/plays/dad-jokes/components/jokeList/jokeList.css
  src/plays/dad-jokes/components/singleJoke/SingleJoke.css
  src/plays/dev-jokes/devJokes.css
  src/plays/digital-delight/components/Categoryfact.css
  src/plays/digital-delight/components/Modal.css
  src/plays/digital-delight/components/TextFact.css
  src/plays/emoji-game/components/welcome.css
  src/plays/github-user-finder/components/InputCard.css
  src/plays/github-user-finder/styles.css
  src/plays/hangman-game/styled-components.tsx
  src/plays/image-gallery/styles.css
  src/plays/inspirational-quotes/card.css
  src/plays/markdown-editor/styles.css
  src/plays/motivate-me/components/cards/index.css
  src/plays/motivate-me/components/search-bar/index.css
  src/plays/pokemon-stats/components/pokecard.css
  src/plays/pokemon-stats/components/search.css
  src/plays/quizeo/components/questions/questions.styles.css
  src/plays/quizeo/pages/score-page/score.styles.css
  src/plays/registration-form/Registration-form.css
  src/plays/why-typescript/wizard/index.css
  src/service-worker.js
Labels: hacktoberfest, hacktoberfest-accepted, waiting for merge

#1348 chore: move to docs folder
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
Labels: waiting for merge, 🟩 priority: low

#1306 chore: add Tip Calculator #1277
  src/plays/tip-calculator/Readme.md
  src/plays/tip-calculator/TipCalculator.jsx
  src/plays/tip-calculator/components/BillAmount.jsx
  src/plays/tip-calculator/components/DisplayCard.jsx
  src/plays/tip-calculator/components/PeopleAmount.jsx
  src/plays/tip-calculator/components/TipAmount.jsx
  src/plays/tip-calculator/styles.css
Labels: play request, hacktoberfest, hacktoberfest-accepted, waiting for merge

#1261 feat(play/URL-Shortner): add URL shortener component
  src/plays/url-shortner/Readme.md
  src/plays/url-shortner/UrlShortner.jsx
  src/plays/url-shortner/cover.jpg
Labels: hacktoberfest, hacktoberfest-accepted, waiting for merge

#1323 feat: Search plays parallelly with typing
  src/common/search/SearchPlays.jsx
Labels: hacktoberfest, hacktoberfest-accepted, waiting for merge

#1356 fix: wordle tiles rendering on every user interaction
  src/plays/wordle/Wordle.tsx
  src/plays/wordle/components/WordleRow.tsx
Labels: bug, hacktoberfest, 🛠 goal: fix, 💻 aspect: code

#1370 ✨ [Feature]: Copy to Clipboard Feature in Wordle Play
  src/plays/wordle/Wordle.tsx
  src/plays/wordle/assets/share.svg
  src/plays/wordle/components/ClipboardModal.tsx
  src/plays/wordle/components/WordleRow.tsx
  src/plays/wordle/components/WordleTile.tsx
  src/plays/wordle/styles.css
  src/plays/wordle/utils.ts
Labels: hacktoberfest, hacktoberfest-accepted, waiting for merge, changes required
