Repository reactplay/react-play, pull requests merged in 2023-02, with the labels that each got.

#939 [#2PlaysAMonth]: Expense tracker
  src/plays/expenses-tracker/ExpensesTracker.tsx
  src/plays/expenses-tracker/Readme.md
  src/plays/expenses-tracker/components/modal.tsx
  src/plays/expenses-tracker/cover.png
Labels: Review-InProgress, #2PlaysAMonth

#942 [#2PlaysAMonth]: Dad Jokes
  .env.development
  src/plays/dad-jokes/DadJokes.js
  src/plays/dad-jokes/Readme.md
  src/plays/dad-jokes/components/categoryModal/CategoryModal.css
  src/plays/dad-jokes/components/categoryModal/CategoryModal.jsx
  src/plays/dad-jokes/components/jokeList/jokeList.css
  src/plays/dad-jokes/components/jokeList/jokeList.jsx
  src/plays/dad-jokes/components/singleJoke/SingleJoke.css
  src/plays/dad-jokes/components/singleJoke/SingleJoke.jsx
  src/plays/dad-jokes/cover.png
  src/plays/dad-jokes/laughing-emoji.gif
  src/plays/dad-jokes/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#957 [#2PlaysAMonth]: Random Quote Card Generator
  package.json
  src/plays/random-quote-card-generator/Components/CardContainer.js
  src/plays/random-quote-card-generator/Components/SideBarDesign.js
  src/plays/random-quote-card-generator/Components/SideBarOperation.js
  src/plays/random-quote-card-generator/RandomQuoteCardGenerator.js
  src/plays/random-quote-card-generator/Readme.md
Labels: Review-InProgress, #2PlaysAMonth

#969 sticky notes app completed
  src/plays/sticky-notes/App.js
  src/plays/sticky-notes/Readme.md
  src/plays/sticky-notes/StickyNotes.js
  src/plays/sticky-notes/components/Form.js
  src/plays/sticky-notes/components/Note.js
  src/plays/sticky-notes/cover.png
  src/plays/sticky-notes/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#943 [#2PlaysAMonth]:Github UserFinder Completed
  src/common/badges-dashboard/badge.css
  src/common/playleaderboard/leaderBoard.css
  src/common/playlists/playlist.css
  src/common/utils/commonUtils.js
  src/plays/dad-jokes/Readme.md
  src/plays/dad-jokes/components/jokeList/jokeList.css
  src/plays/github-user-finder/GithubUserFinder.js
  src/plays/github-user-finder/Readme.md
  src/plays/github-user-finder/components/InputCard.css
  src/plays/github-user-finder/components/InputCard.jsx
  src/plays/github-user-finder/components/ProfileCard.jsx
  src/plays/github-user-finder/context/ResultContext.jsx
  src/plays/github-user-finder/cover.png
  src/plays/github-user-finder/styles.css
  src/plays/random-quote-card-generator/RandomQuoteCardGenerator.js
  src/plays/random-quote-card-generator/Readme.md
  src/plays/sticky-notes/Readme.md
  src/plays/sticky-notes/StickyNotes.js
  src/plays/sticky-notes/styles.css
  src/plays/tenzies-game/Readme.md
  src/plays/tenzies-game/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#984 [#2PlaysAMonth]: Video to MP3 Converter
  src/plays/tube2tunes/Readme.md
  src/plays/tube2tunes/Tube2tunes.js
  src/plays/tube2tunes/components/Loader.js
  src/plays/tube2tunes/components/loader.css
  src/plays/tube2tunes/components/tubeTuneLogo.svg
  src/plays/tube2tunes/components/utils.js
  src/plays/tube2tunes/cover.png
  src/plays/tube2tunes/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#983 [#2PlaysAmonth] NoteHack
  src/plays/notehack/Notehack.js
  src/plays/notehack/Readme.md
  src/plays/notehack/components/addNote/AddNote.css
  src/plays/notehack/components/addNote/AddNote.js
  src/plays/notehack/components/header/Header.css
  src/plays/notehack/components/header/Header.js
  src/plays/notehack/components/noteList/NoteList.css
  src/plays/notehack/components/noteList/NoteList.js
  src/plays/notehack/components/singleNote/SingleNote.css
  src/plays/notehack/components/singleNote/SingleNote.js
  src/plays/notehack/cover.png
  src/plays/notehack/styles.css
Labels: #2PlaysAMonth

#977 [#2PlaysAmonth] Roll The Dice - is a react game.
  src/plays/roll-the-dice/Readme.md
  src/plays/roll-the-dice/RollTheDice.js
  src/plays/roll-the-dice/assets/1.png
  src/plays/roll-the-dice/assets/2.png
  src/plays/roll-the-dice/assets/3.png
  src/plays/roll-the-dice/assets/4.png
  src/plays/roll-the-dice/assets/5.png
  src/plays/roll-the-dice/assets/6.png
  src/plays/roll-the-dice/assets/close.png
  src/plays/roll-the-dice/assets/guide/guide-1.jpg
  src/plays/roll-the-dice/assets/guide/guide-2.jpg
  src/plays/roll-the-dice/assets/guide/guide-3.jpg
  src/plays/roll-the-dice/assets/guide/guide-4.jpg
  src/plays/roll-the-dice/assets/guide/guide-5.jpg
  src/plays/roll-the-dice/assets/guide/guide-6.jpg
  src/plays/roll-the-dice/assets/guide/guide-7.jpg
  src/plays/roll-the-dice/assets/guide/guide-8.jpg
  src/plays/roll-the-dice/assets/help.png
  src/plays/roll-the-dice/assets/trophy.png
  src/plays/roll-the-dice/components/App.jsx
  src/plays/roll-the-dice/components/Game.jsx
  src/plays/roll-the-dice/components/Guide.jsx
  src/plays/roll-the-dice/components/Player.jsx
  src/plays/roll-the-dice/components/SelectPlayer.jsx
  src/plays/roll-the-dice/components/Winner.jsx
  src/plays/roll-the-dice/constant/guide.js
  src/plays/roll-the-dice/context/diceContext.jsx
  src/plays/roll-the-dice/cover.png
  src/plays/roll-the-dice/hooks/useGame.js
  src/plays/roll-the-dice/hooks/useRandom.js
  src/plays/roll-the-dice/hooks/useStep.js
  src/plays/roll-the-dice/roll-the-dice.css
  src/plays/roll-the-dice/utils/randomNumber.js
Labels: #2PlaysAMonth

#970 [#2PlaysAMonth]: Small Editing App
  src/plays/photoshopapp/Constants.js
  src/plays/photoshopapp/Photoshopapp.js
  src/plays/photoshopapp/Readme.md
  src/plays/photoshopapp/SidebarItem.js
  src/plays/photoshopapp/Slider.js
  src/plays/photoshopapp/cover.png
  src/plays/photoshopapp/styles.css
Labels: review ready, #2PlaysAMonth

#986 fixed empty notes adding bug
  src/plays/sticky-notes/App.js
Labels: bug

#972 [#2PlaysAMonth]: Cricket Game
  package.json
  src/plays/cricket-game/CricketGame.js
  src/plays/cricket-game/Readme.md
  src/plays/cricket-game/assets/ball.svg
  src/plays/cricket-game/assets/bat.svg
  src/plays/cricket-game/assets/batsman.png
  src/plays/cricket-game/assets/cricket-ground.jpg
  src/plays/cricket-game/assets/cricket-logo.png
  src/plays/cricket-game/assets/hitwicket.svg
  src/plays/cricket-game/assets/homepage.jpg
  src/plays/cricket-game/assets/pitch.svg
  src/plays/cricket-game/assets/wicket.svg
  src/plays/cricket-game/audios/crowd-cheering.mp3
  src/plays/cricket-game/audios/crowd-disappointed.mp3
  src/plays/cricket-game/audios/gametrackbg.mp3
  src/plays/cricket-game/audios/shotSound.mp3
  src/plays/cricket-game/audios/wicketHit.mp3
  src/plays/cricket-game/components/CommentaryTimeline.js
  src/plays/cricket-game/components/EndGameScreen.js
  src/plays/cricket-game/components/InfoBox.js
  src/plays/cricket-game/components/Modal.js
  src/plays/cricket-game/components/Pitch.js
  src/plays/cricket-game/components/Score.js
  src/plays/cricket-game/components/ScorePanel.js
  src/plays/cricket-game/components/TopBar.js
  src/plays/cricket-game/game/commentary.js
  src/plays/cricket-game/game/gameLogic.js
  src/plays/cricket-game/game/levels.js
  src/plays/cricket-game/game/utils.js
  src/plays/cricket-game/styles.css
Labels: #2PlaysAMonth

#964 [#2PlaysAMonth]: Smart Converter
  src/plays/smart-converter/Readme.md
  src/plays/smart-converter/SmartConverter.js
  src/plays/smart-converter/components/TextForm.js
  src/plays/smart-converter/cover.png
  src/plays/smart-converter/styles.css
Labels: Review-InProgress, #2PlaysAMonth

#944 [#2PlaysAMonth]: Calculator
  package.json
  src/plays/simple-calculator/Readme.md
  src/plays/simple-calculator/SimpleCalculator.js
  src/plays/simple-calculator/components/Buttons.js
  src/plays/simple-calculator/components/Calculator.js
  src/plays/simple-calculator/components/Display.js
  src/plays/simple-calculator/cover.png
  src/plays/simple-calculator/styles/Buttons.css
  src/plays/simple-calculator/styles/Calculator.css
  src/plays/simple-calculator/styles/Display.css
Labels: Review-InProgress, #2PlaysAMonth
