Repository reactplay/react-play, pull requests merged in 2023-11, with the labels that each got.

#1350 feat: play search result summary
  src/common/playlists/PlayList.jsx
  src/common/playlists/playlist.css
Labels: waiting for reviewers, hacktoberfest, hacktoberfest-accepted

#1387 fix: bug fix for favicon not visible on new tabs/plays
  public/index.html
Labels: waiting for merge

#1395 refactor: home component refactoring
  src/common/home/Home.jsx
  src/common/home/HomeBanner.jsx
  src/common/home/HomeContent.jsx
  src/common/home/HomeContributors.jsx
  src/common/home/HomeFeatures.jsx
  src/common/home/HomeIdeas.jsx
  src/common/home/HomePlays.jsx
  src/common/home/HomeSponsors.jsx
  src/common/home/HomeTestimonials.jsx
Labels: waiting for merge, changes required

#1397 fix: @faker-js/faker deprecation
  src/common/utils/fakeUser.js
Labels: waiting for merge
