Repository reactplay/react-play, pull requests merged in 2024-10, with the labels that each got.

#1525 fix: styling with filter owner (#1518)
  src/common/search/FilterPlays.jsx
Labels: hacktoberfest, 💻 aspect: code, 🤖 aspect: dx

#1527 feat: share button to share plays (#1522)
  src/common/playlists/PlayCard.jsx
  src/common/playlists/PlayShare.jsx
Labels: hacktoberfest

#1528 Automatic Unassign Hacktoberfest Issues workflow
  .github/workflows/issue-unassign.yml
Labels: hacktoberfest

#1541 Feature: Added a play named Random Avatar
  src/plays/random-avatar/RandomAvatar.js
  src/plays/random-avatar/Readme.md
  src/plays/random-avatar/styles.css
Labels: hacktoberfest, changes required

#1539 Changes to be committed: Added Cheesy Pick-up lines Play
  src/plays/cheesylines/Cheesylines.js
  src/plays/cheesylines/Readme.md
Labels: hacktoberfest

#1549 Merge Request: New Play - BMI Calculator
  src/plays/bodymassindex-calculator/BodymassindexCalculator.js
  src/plays/bodymassindex-calculator/Readme.md
  src/plays/bodymassindex-calculator/cover.jpg
  src/plays/bodymassindex-calculator/styles.css
Labels: hacktoberfest, changes required

#1553 (refactor) coverImageUtil, fakeUser and formatCount common/utils methods
  src/common/utils/coverImageUtil.js
  src/common/utils/fakeUser.js
  src/common/utils/formatCount.ts
  src/common/utils/utilsConstants.js
Labels: hacktoberfest, 🛠 goal: refactor

#1554 Feature/play/zoomlogin refactor1
  src/plays/zoomlogin/MainPage.js
  src/plays/zoomlogin/assets/apple-logo.png
  src/plays/zoomlogin/assets/apple-logo.svg
  src/plays/zoomlogin/assets/copyright.svg
  src/plays/zoomlogin/assets/facebook-logo.svg
  src/plays/zoomlogin/assets/github.svg
  src/plays/zoomlogin/assets/google-logo.png
  src/plays/zoomlogin/assets/google-logo.svg
  src/plays/zoomlogin/assets/linkedin-logo.png
  src/plays/zoomlogin/assets/linkedin.svg
  src/plays/zoomlogin/assets/linkedinImg.png
  src/plays/zoomlogin/components/Zoom/ZoomSignin.js
  src/plays/zoomlogin/components/chatbot/widget/InitialButtonOptions.jsx
Labels: play request, hacktoberfest

#1557 fix: Ensure consistent checkbox behavior in Language filter (#1519)
  src/common/search/FilterPlays.jsx
Labels: hacktoberfest

#1561 (refactor) constant/index.js file
  src/common/footer/ExtendedFooter.jsx
  src/common/header/HeaderNav.jsx
  src/common/playcreated/PlayCreated.jsx
  src/common/playideas/PlayIdeas.jsx
  src/common/playlists/PlayList.jsx
  src/constants/index.js
  src/plays/navbar/Backgrounds.js
Labels: hacktoberfest

#1558 (feat) Improved UI of play Typing Speed Test
  src/common/search/search.css
  src/plays/bodymassindex-calculator/Readme.md
  src/plays/bodymassindex-calculator/styles.css
  src/plays/cheesylines/Readme.md
  src/plays/random-avatar/Readme.md
  src/plays/typing-speed-test/TypingSpeedTest.jsx
  src/plays/typing-speed-test/components/ResultModal.jsx
  src/plays/typing-speed-test/components/Statistics.jsx
  src/plays/typing-speed-test/components/Stats.jsx
  src/plays/typing-speed-test/components/Timer.jsx
  src/plays/typing-speed-test/components/TypingTest.jsx
  src/plays/typing-speed-test/components/Word.jsx
  src/plays/typing-speed-test/context/TypingTestContext.js
  src/plays/typing-speed-test/cover.png
  src/plays/typing-speed-test/readme.md
  src/plays/typing-speed-test/styles.css
  src/plays/typing-speed-test/utils/index.js
Labels: hacktoberfest

#1565 fix: Made clickable links and made badges page responsive
  src/common/badges-dashboard/Badge.jsx
  src/common/badges-dashboard/BadgeDetails.jsx
Labels: hacktoberfest, 💻 aspect: code

#1564 Daily Diary
  src/plays/daily-journa/DailyJournal.jsx
  src/plays/daily-journa/Readme.md
  src/plays/daily-journa/components/EntryDetails.jsx
  src/plays/daily-journa/components/EntryList.jsx
  src/plays/daily-journa/components/JournalEntryForm.jsx
  src/plays/daily-journa/styles.css
Labels: hacktoberfest

#1567 feat(plays): add dictionary play
  src/plays/dictionary/Dictionary.js
  src/plays/dictionary/DictionaryContainer.jsx
  src/plays/dictionary/Readme.md
Labels: hacktoberfest
