Repository reactplay/react-play, pull requests merged in 2024-02, with the labels that each got.

#1429 typo "healps" replaced with "helps"
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: waiting for reviewers, waiting for merge

#1417 PR - Fixed The Activites After Auth
  .env.development
  src/common/routing/RouteDefs.jsx
Labels: waiting for reviewers, waiting for merge

#1377 fix: search bar responsiveness mobile view
  src/common/search/FilterPlays.jsx
  src/common/search/SearchBox.jsx
  src/common/search/search.css
Labels: waiting for reviewers, waiting for merge

#1446 fixed : #1442 added instargam and linkedin icons to the footer
  src/common/footer/ExtendedFooter.jsx
Labels: waiting for reviewers, waiting for merge

#1457 feat(ci): add release-drafter ci/cd github action for automatic releases
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: waiting for reviewers, ready to merge, ⭐ goal: addition, 💻 aspect: code

#1454 refactor: navbar's social icons items
  src/common/header/HeaderNav.jsx
Labels: 🛠 goal: refactor, ready to merge

#1437 chore: add meetup link icon in the footer
  src/common/footer/ExtendedFooter.jsx
Labels: ready to merge, chore

#1445 feat(plays): add accordion to play project.
  src/plays/accordian/Accordian.jsx
  src/plays/accordian/AccordianData.jsx
  src/plays/accordian/Readme.md
  src/plays/accordian/cover.png
  src/plays/accordian/data.js
  src/plays/accordian/styles.css
Labels: waiting for reviewers, changes required

#1444 feat:add discord icon to header
  src/common/header/HeaderNav.jsx
  src/common/header/header.css
Labels: ready to merge, chore

#1458 fix: #1452 Testimonial card position
  src/common/Testimonial/TestimonialCard.jsx
Labels: ready to merge, 🛠 goal: fix

#1464 fix: replace to meetup link
  src/common/defaultBanner/DefaultBanner.jsx
Labels: ready to merge, 🛠 goal: fix

#1463 fix: position of browse and create buttons #1424
  package.json
  pnpm-lock.yaml
  src/App.css
  src/common/footer/ExtendedFooter.jsx
  src/common/home/Home.jsx
  src/common/home/home.css
  src/common/playlists/playlist.css
  src/plays/accordian/Readme.md
  src/plays/accordian/styles.css
  src/plays/airbnb-experiences-clone/Readme.md
  src/plays/airbnb-experiences-clone/styles.css
  src/plays/emojipedia/Emojipedia.jsx
  src/plays/quiz-app/QuizApp.tsx
  src/plays/savings-calculator/components/SavingOptions/savingOptions.scss
  src/plays/savings-calculator/styles/savingsCalculator.scss
  src/plays/schulte-tables/Readme.md
  src/plays/schulte-tables/styles.css
  src/plays/url-shortner/Readme.md
  src/plays/wordle/styles.css
Labels: ready to merge, 🛠 goal: fix

#1466 chore: remove unwanted code
  src/common/playlists/PlayHeaderActions.jsx
  src/index.css
  src/index.jsx
Labels: chore

#1461 fix: play cards ui
  src/common/playlists/PlayCard.jsx
  src/common/playlists/PlayThumbnail.jsx
  src/common/playlists/playlist.css
Labels: 🛠 goal: fix

#1471 Fix/ Position of the Banner
  src/common/playlists/playlist.css
Labels: 🛠 goal: fix

#1474 fix(ui): resolve footer position bug
  src/App.css
Labels: 🛠 goal: fix

#1475 Fix the header items alignment
  src/common/header/Header.jsx
  src/common/header/header.css
  src/common/search/search.css
Labels: 🛠 goal: fix
