Repository reactplay/react-play, pull requests merged in 2024-01, with the labels that each got.

#1415 fix(common): focus fix on play filter modal open
  src/common/modal/index.jsx
  src/common/search/FilterPlays.jsx
Labels: waiting for reviewers, waiting for merge

#1422 fix(plays): remove redundant css to fix bug#1420
  src/plays/schulte-tables/styles.css
Labels: waiting for merge

#1421 feat: improved website accessibility, best practices, seo score to 100%
  src/App.css
  src/common/defaultBanner/DefaultBanner.jsx
  src/common/footer/Footer.jsx
  src/common/home/HomeIdeas.jsx
  src/common/home/Sponsors.jsx
Labels: waiting for reviewers, waiting for merge

#1418 fix: homepage navigation #741
  package.json
  src/App.css
  src/common/header/Header.jsx
  src/common/header/header.css
  src/common/home/home.css
Labels: waiting for merge

#1368 feat(play/airbnb-experiences-clone): add airbnb-experiences-clone
  src/plays/airbnb-experiences-clone/AirbnbExperiencesClone.jsx
  src/plays/airbnb-experiences-clone/App.jsx
  src/plays/airbnb-experiences-clone/Readme.md
  src/plays/airbnb-experiences-clone/assets/images/airbnb-logo.png
  src/plays/airbnb-experiences-clone/assets/images/katie-zaferes.png
  src/plays/airbnb-experiences-clone/assets/images/mountain-bike.png
  src/plays/airbnb-experiences-clone/assets/images/photo-grid.png
  src/plays/airbnb-experiences-clone/assets/images/star.png
  src/plays/airbnb-experiences-clone/assets/images/wedding-photography.png
  src/plays/airbnb-experiences-clone/components/Card.jsx
  src/plays/airbnb-experiences-clone/components/Hero.jsx
  src/plays/airbnb-experiences-clone/components/Navbar.jsx
  src/plays/airbnb-experiences-clone/cover.png
  src/plays/airbnb-experiences-clone/data.js
  src/plays/airbnb-experiences-clone/styles.css
Labels: waiting for reviewers, changes required
