Repository reactplay/react-play, pull requests merged in 2024-04, with the labels that each got.

#1487 fix: hover behavior in trending plays
  src/common/playlists/playlist.css
Labels: 🛠 goal: fix

#1481 added testcases covering all major browsers, removed cypress & added playwright 🧪
  .github/workflows/playwright-e2e.yml
  .gitignore
  README.md
  cypress.config.ts
  cypress/e2e/homePage.cy.ts
  cypress/e2e/ideasPage.cy.ts
  cypress/e2e/leaderboardPage.cy.ts
  cypress/support/commands.ts
  cypress/support/constant.ts
  cypress/support/e2e.ts
  e2e/README.md
  e2e/pageobjects/enums/constant.ts
  e2e/pageobjects/pages/home.ts
  e2e/pageobjects/pages/ideas.ts
  e2e/pageobjects/pages/plays.ts
  e2e/pageobjects/pages/testimonials.ts
  e2e/tests/homepage.spec.ts
  e2e/tests/ideaspage.spec.ts
  e2e/tests/playspage.spec.ts
  e2e/tests/testimonialspage.spec.ts
  package.json
  playwright.config.ts
  pnpm-lock.yaml
Labels: waiting for reviewers, ✨ goal: improvement

#1488 Translation app built and cover image added
  src/plays/language-translater/LanguageTranslater.jsx
  src/plays/language-translater/Languages.jsx
  src/plays/language-translater/Readme.md
  src/plays/language-translater/cover.png
  src/plays/language-translater/icons/Copy.svg
  src/plays/language-translater/icons/Expand_down.svg
  src/plays/language-translater/icons/Horizontal_top_left_main.svg
  src/plays/language-translater/icons/Sort_alfa.svg
  src/plays/language-translater/icons/hero_img.jpg
  src/plays/language-translater/icons/logo.svg
  src/plays/language-translater/icons/sound_max_fill.svg
  src/plays/language-translater/styles.css
Labels: play request
